version: "3.9"

services:
  fastapi:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      UPLOAD_DIR: /app/media/uploaded_videos
      TRIMMED_DIR: /app/media/trimmed_videos
      MAX_WORKERS: 4
      CHUNK_SIZE: 10485760
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/video_trimming_db
      PROTOCOL: http
      PORT: 8000
      BASE_URL: localhost
      COMPLETE_BASE_URL: http://localhost:8000
    volumes:
      - .:/app
      - ./media:/app/media
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_trimming_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: