name: DevSecOps Pipeline

on:
  push:
    branches:
      - master_prashant # Run the pipeline only for this branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      #only High-Priority Rules
      - name: Run Linter (Flake8)
        run: |
          pip install flake8
          flake8 --select=F401,F841,E999,F821,F632,E722,E402 --max-line-length=100 .
        #  flake8 --select=F841,E999,F821,F632,E402 --max-line-length=100 .
